name: Generate Windstations Web

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Test Euskalmet
        run: |
          curl -I -L https://www.euskalmet.euskadi.eus

      - name: Test JSON Euskalmet
        run: |
          curl -v https://www.euskalmet.euskadi.eus/vamet/stations/readings/C042/2026/07/02/webmet00-readingsData.json
      - name: Generar HTML
        run: |
          python generate.py

      - name: Guardar cambios
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add index.html
          git commit -m "Update wind data" || echo "No changes"

          git push
       - name: Esperar a Pages
run: |
    TARGET="$(date '+%d/%m/%Y %H:%M')"

    for i in {1..60}; do
      echo "Comprobación $i"

      if curl -s https://aayani69.github.io/Windstations/ | grep -q "$TARGET"; then
        echo "Nueva versión detectada"
        exit 0
      fi

      sleep 10
    done

    echo "Timeout esperando Pages"
    exit 1
